### ISSUE TITLE
mruby Bindings

### ISSUE THREAD

**Issue by IceDragon200** [SFML/SFML-Website#101]
Hello, I would like to submit my mruby bindings for SFML, I've sent an email before with all the information so I'll just quote it here.

Original Email

> I created some mruby bindings way back, they should still be working, as I wrote them against SFML 2.4
>
> Due to the nature of mruby's gems, each module is split across different repositories
>
> https://github.com/IceDragon200/mruby-sfml
https://github.com/IceDragon200/mruby-sfml-audio
https://github.com/IceDragon200/mruby-sfml-graphics
https://github.com/IceDragon200/mruby-sfml-network
https://github.com/IceDragon200/mruby-sfml-system
https://github.com/IceDragon200/mruby-sfml-window
>
> The only things that mostly work would be the Audio, Graphics, System and Window.
>
> Network was kinda complicated for mruby so I don't think I ever finished it.
>
> But for prototyping, everything else is there.
> Mruby, just for reference
>
> https://github.com/mruby/mruby

I'll work on updating the READMEs

**Comment by eXpl0it3r** [comment]
Cool, thanks for putting it here!

We'll simply link the "main" repository (https://github.com/IceDragon200/mruby-sfml).

**Comment by eXpl0it3r** [comment]
Finally gotten around to adding it in 21f949415f1b8a2849f0565502625ce9cab5a232
