### ISSUE TITLE
View tutorial uses the .f suffix for floats inconsistently

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#104]
For example

```
view.setViewport(sf::FloatRect(0.25f, 0.25, 0.5f, 0.5f));
```

I think it's best to use .f everywhere where a float is used.

**Comment by slx7R4GDZM** [comment]
I noticed this but it isn't just the view tutorial, it's almost every graphics one and maybe some others.

**Comment by eXpl0it3r** [comment]
Yes, I started a fix once, but then noticed it's a bunch of file and created the issue instead. 😄

**Comment by eXpl0it3r** [comment]
Fixed in c56431683c78ea5dc8316be0e34b3f947afb0019
