### ISSUE TITLE
Add invite for Discord to the community website

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#106]
Not fully discussed but with increase in popularity of Discord and the better accessibility for it, it might be a good idea to add a permanent invite to the already existing SFML Discord server next to the IRC links.

Any comments from the @SFML/sfml Team?

Permanent invite link: https://discord.gg/gPBHzJ8

**Comment by MarioLiebisch** [comment]
Yeah, sure, why not? Haven't seen any invite link though. :D

**Comment by eXpl0it3r** [comment]
It was more a discussion, but I guess in case someone wants to check it out, I added a link.

**Comment by mantognini** [comment]
I've no strong opinion about this.

**Comment by TankOs** [comment]
Go for it.

**Comment by eXpl0it3r** [comment]
Implemented with #109
