### ISSUE TITLE
Add CMake guide to website "Getting Started" section

### ISSUE THREAD

**Issue by gale93** [SFML/SFML-Website#114]
A CMake script that init a new empty project, like [this one](https://en.sfml-dev.org/forums/index.php?topic=24070.0) should be on the website's "Getting Started" section because it's really handy to have ( For new & old users )

**Comment by eXpl0it3r** [comment]
It's not relevant, as we won't be supporting premake. If it can be done by the user, then that's fine, but it's not something official, nor has it relevance for the CMake tutorial. 😉

**Comment by eXpl0it3r** [comment]
With #167 we've added a link to the https://github.com/SFML/cmake-sfml-project and some additional words https://www.sfml-dev.org/tutorials/2.6/start-cmake.php
