### ISSUE TITLE
Host migration

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#117]
There are a few things that need adjustment as an effect of moving the hosting of the website and everything else managed by @TankOs. So we can more easily track it, I've created this issue.

* [X] HTTPS enforcement with the exception of `ip-provider.php`
* [x] Setup IRC
* [x] Setup redirects for documentation and tutorials
* [x] Setup custom error pages
* [x] Analyse & fix `à` UTF-8 issue on the French forum
* [ ] Reimplement file download mirroring
* [ ] ~Setup Web IRC~
* [ ] ~SSH access for artifact upload~
    * [ ] ~Alternatively change sync to FTPS~
    * [x] Alternatively use a different host
* [ ] SSH access for artifact mirroring sync
    * [ ] Alternatively change sync to FTPS
* [x] Consider options for hosting binaries also on GitHub

Add stuff if you see something broken. 🙂

**Comment by LaurentGomila** [comment]
Strangely, now the 'à' character produces '?' on the french forum, while 'é' is displayed correctly. Looking at the page source, everything seems to be using UTF-8 🤔

**Comment by eXpl0it3r** [comment]
It's fine here, I'll try to look into it (with @TankOs) as soon as possible.
We did have some migration issues with UTF-8 and SMF's UTF-8 "support" is well "support". 😄

We should seriously look into other options for forum software, SMF is just horrible and you never know when it stops working (we already had to manually patch the subforum mod...).

**Comment by LaurentGomila** [comment]
If it's such a pain to maintain, why not.

**Comment by LaurentGomila** [comment]
The issue with 'à' is checked in your list, but the problem is still there :/

**Comment by eXpl0it3r** [comment]
@TankOs told me there was a db schema issue that he fixed, but I guess it didn't actually fix stuff. I'll let him know again.

**Comment by eXpl0it3r** [comment]
Sorry, I've told Tank and then forgot to recheck myself later on. I'll see what I can find out. 🙂

**Comment by eXpl0it3r** [comment]
It's fixed now. Ugh SMF is such a bad piece of software. 😫

When Tank did the change for the language files he wrote `utf-8`, but the code determining if utf8 is used does a string comparison against `UTF-8`, which then obviously failed. And since à is \xA0 but \xA0 can also mean non-breaking space in certain encodings, it repalced à with non-breaking spaces, not sure what's up with the ? but oh well, it's fixed now...

**Comment by LaurentGomila** [comment]
I confirm it is working perfectly. Thank you very much!

:tada:

**Comment by eXpl0it3r** [comment]
IRC isn't really used anymore that would justify a web front-end, so I crossed that off the list.  
We're now also hosting the downloads on each GitHub release.

The remaining open points, have been moved to a dedicated issue: #166
