### ISSUE TITLE
The CSFML source download is one commit behind the 2.5 tag

### ISSUE THREAD

**Issue by crumblingstatue** [SFML/SFML-Website#120]
It doesn't seem to include https://github.com/SFML/CSFML/commit/61f17e3c1d109b65ef7e3e3ea1d06961da130afc , which is marked as the 2.5 release.

I'm specifically talking about the source archive, which is https://www.sfml-dev.org/files/CSFML-2.5-sources.zip .

I don't know about the binary releases.

**Comment by eXpl0it3r** [comment]
Thanks for letting us know. I did a sneaky re-tag, because of the one change and forgot to update the source. It's updated now. 🙂
