### ISSUE TITLE
The chat in browser now button and link are broken

### ISSUE THREAD

**Issue by fwSmit** [SFML/SFML-Website#130]
When on the page [https://www.sfml-dev.org/community.php](https://www.sfml-dev.org/community.php) you can click on the big 'chat now' button or the equivalent link. When clicking on one of those you will get redirected to a [Web Server's Default Page](https://chat.sfml-dev.org/).
I would suggest either fixing the https://chat.sfml-dev.org/ website or removing the links

**Comment by eXpl0it3r** [comment]
I was hoping we could bring back the browser IRC client, but currently the situation doesn't look like we will any time soon, so it's best to remove it now and thanks to git the history isn't lost. 😉

**Comment by eXpl0it3r** [comment]
Removed with b793b5a427125b03343b6090feab53ac8cd97a8b
