### ISSUE TITLE
2.5 tutorial links still point to 2.5.0 documentation

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#132]
Reported on the [forum](https://en.sfml-dev.org/forums/index.php?topic=25691.0) the tutorial links for SFML 2.5 still point to the documentation for SFML 2.5.0 instead of 2.5.1.

IIRC there's some PHP variable that needs adjusting.

**Comment by LaurentGomila** [comment]
Here: https://github.com/SFML/SFML-Website/blob/master/tutorials/2.5/header.php#L3

**Comment by eXpl0it3r** [comment]
Fixed with 23244b914e5648cdc17bbc9dc0aa656b29365791
