### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by fr0zi** [SFML/SFML-Website#133]
Hello,
I can't get into SFML website on http://www.sfml-dev.org.
I'm getting Error: 504 - Gateway Time-out

**Comment by eXpl0it3r** [comment]
Thanks for letting us know. It's being worked on right now and you can find status updates on Twitter: https://twitter.com/sfmldev

**Comment by fr0zi** [comment]
No problem :) I will observe your Twitter :)

**Comment by eXpl0it3r** [comment]
The Website is fully reachable again 🙂

**Comment by fr0zi** [comment]
Yeap, thanks :)
