### ISSUE TITLE
Website inaccessible in Turkey

### ISSUE THREAD

**Issue by DenizBasgoren** [SFML/SFML-Website#137]
When I try to enter your website, i get redirected somewhere.

http://88.255.216.16/landpage?op=1&ms=http://sfml-dev.org/

If I try to go to /documentation/2.5.1, then I get the following error on my Firefox:

SSL_ERROR_RX_RECORD_TOO_LONG

Could you please host your documentation elsewhere, like for example on Github pages? And, do you permit me to copy and host the docs website elsewhere?

**Comment by eXpl0it3r** [comment]
We're currently looking into the issue. In the meantime you can find all the downloads including the documentation here: https://github.com/SFML/SFML/releases/tag/2.5.1

**Comment by TankOs** [comment]
@DenizBasgoren Thanks for reporting.

We have received multiple reports from Turkey from people having problems connecting to SFML's website. At the moment I think it's a national issue in your country. What leads me to this conclusion is:

- If our server would just not be reachable from you, then you would not have been redirected in any way. This might also be caused by a browser extension or your ISP. Please try https://sfml-dev.org/ instead of http://sfml-dev.org/.
- I checked a specific IP from Turkey against our spam block list, no match.
- SSL_ERROR_RX_RECORD_TOO_LONG is usually seen when HTTPS is expected, but HTTP is served.
- Website is perfectly reachable from here: https://downforeveryoneorjustme.com/sfml-dev.org

Can you please send me your public IP address, so I can check yours with our blacklist as well? You can grab it here, for example: http://checkip.dyndns.org/

**Comment by eXpl0it3r** [comment]
From the reports I got, some have reported to receive a timeout when trying to access the HTTP URL: http://sfml-dev.org/ip-provider.php

If anyone knows how to get a site unblocked, let us know.

**Comment by DenizBasgoren** [comment]
My public ip, as reported by dyndns is  37.154.231.202. I'll post some more info to help you track the problem out.

Last time I tried to access your website was 5 months ago, and I had no problems. This is the first time I tried to enter ever since.

http://sfml-dev.org/ redirects me to the above mentioned ip (which i found out to be of isp), after a wait of 5 seconds the first time, and after no wait after the second time.

https://sfml-dev.org fails immediately with the error (on firefox)

Secure Connection Failed

An error occurred during a connection to sfml-dev.org. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

on chrome mobile, the https link first redirected to the isp's ip, then redirected to the error page with the following error

This site can’t provide a secure connection
sfml-dev.org sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by mertcanekiz** [comment]
I am also facing the same issue, both from desktop and mobile data.

**Comment by eXpl0it3r** [comment]
I was informed that it's apparently possible to get the domain unlisted from the [block list](https://www.usom.gov.tr/url-list.txt), but unfortunately, when trying to access the URL, the request simply times out. Maybe they only allow access from inside Turkey?

Can anyone access the following URL and if you can, would it be possible to fill out the form or get us the contact details, so we can send an unblock request?

https://www.usom.gov.tr/iletisim.html

**Comment by mertcanekiz** [comment]
The page does not have a contact form as far as I can see, but the contact details are:

**Comment by eXpl0it3r** [comment]
If you could provide a translation (and/or suggestions) to the follow text, so I can send both English & Turkish texts and hope that they accept emails from outside Turkey...

> Dear Sir or Madam
> In recent months it has come to our attention that our website's domain [1] has been blocked in Turkey [2]. The Simple and Fast Multimedia Library (SFML) [3] is an open source C++ library [4] and widely used as teaching tool by universities. There are a lot of people all around the world creating games or learning C++ with the help of SFML.
> We believe our domain (sfml-dev.org) was blocked by accident and would kindly ask you to remove us from the blocking list.
> 
> Kind regards
> 
> [1] https://www.sfml-dev.org/
> [2] https://github.com/SFML/SFML-Website/issues/137
> [3] https://en.wikipedia.org/wiki/Simple_and_Fast_Multimedia_Library
> [4] https://github.com/SFML/SFML

**Comment by maidis** [comment]
Turkish translation of the e-mail draft::

> Sayın yetkili merhaba,
> 
> Son aylarda internet sitemizin alan adının [1] Türkiye'de engellendiğini fark ettik [2].
> 
> Simple and Fast Multimedia Library (SFML) [3] özgür bir C++ kütüphanesidir [4] ve üniversiteler tarafından öğretim aracı olarak yaygın olarak kullanılmaktadır. Dünyanın her yerinde SFML kullanarak oyun geliştiren ve C++ öğrenen birçok insan vardır.
> 
> Alan adımızın (sfml-dev.org) yanlışlıkla engellendiğine inanıyoruz ve bizi engelleme listesinden çıkarmanızı rica ediyoruz.
> 
> Saygılarımızla,
> SFML Geliştirme Ekibi.
> 
> [1] https://www.sfml-dev.org/
> [2] https://github.com/SFML/SFML-Website/issues/137
> [3] https://en.wikipedia.org/wiki/Simple_and_Fast_Multimedia_Library
> [4] https://github.com/SFML/SFML

**Comment by maidis** [comment]
I have now noticed the reason for this blocking: "-dev".

It seems that someone had tried to block fraudulent sites that imitate the E-Devlet (E-Government Gateway) [1] site without enough control.

[1] https://www.turkiye.gov.tr/ (I do not remember clearly, but I think the old domain name was www.e-devlet.gov.tr.)

**Comment by mertcanekiz** [comment]
@maidis I bet you are right and that is the reason. I hope they understand and fix this soon. 

Also, I can vouch for that translation, looks good.

**Comment by eXpl0it3r** [comment]
Thanks a lot for the translation and double check. I've sent them an email, so let's see how things go. Let us know when you notice that the site is reachable again.

**Comment by maidis** [comment]
I guess there is no feedback from the authorities, right? Shall we email as well as users? Should we contact CIMER [1] or BTK [2]?

[1] https://www.btk.gov.tr/
[2] https://www.cimer.gov.tr/

**Comment by eXpl0it3r** [comment]
Yes, I've not received any response to my email. I guess it can't hurt if others contact them as well.

**Comment by maidis** [comment]
I sent a similar e-mail to usom.gov.tr's both ihbar and iletisim e-mail adresses. It's sad but understandable that such an event has occurred. But it's a very different and important issue that such a situation cannot be solved in such a long time :(

I compiled the SFML API documentation as PDF to make easier of the lives of people living in Turkey a little bit:

https://www.dropbox.com/s/f08sgwqys8myjpt/sfml-refman.pdf

**Comment by eXpl0it3r** [comment]
Note that the documentation as well as the other downloads can be accessed on GitHub as well: https://github.com/SFML/SFML/releases/tag/2.5.1

**Comment by maidis** [comment]
> I was informed that it's apparently possible to get the domain unlisted from the [block list](https://www.usom.gov.tr/url-list.txt), 

It seems that finally they removed SFM's website from the list. 🎉🥳

@mertcanekiz, @DenizBasgoren, Can you access the site without any VPN?

**Comment by mertcanekiz** [comment]
Yes! I can access the website now. Great job everyone, I'm happy this got resolved

**Comment by eXpl0it3r** [comment]
Great news! Thanks for everyone who reached out and I'm sorry for the inconveniences. 🙂
