### ISSUE TITLE
Start with an empty project and not win32

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#14]
The Visual Studio tutorials says to create a win32 project, this however will most of the time lead to issues, since it will automatically add the stdafx.h header, which is a Visual Studio-only feature and most programmers/new comers don't understand what's it for. As such it often just leads to issues. Additionally it might set the subsystem to Window thus requiring the Windows specific entry point.

Personally I always advise to use an empty project, so Visual Studio won't have tweaked anything.

**Comment by eXpl0it3r** [comment]
If nobody has anything against this, I'll change it.

**Comment by zsbzsb** [comment]
:+1:

**Comment by Bromeon** [comment]
I agree, empty projects are fine.

**Comment by binary1248** [comment]
:+1:

If I bother using IDEs, I always go for empty projects. All the auto-generated stuff just clutters up the workspace, and that can indeed be confusing for beginners.

**Comment by eXpl0it3r** [comment]
Fixed with #121
