### ISSUE TITLE
Documentation/Tutorial redirects in .htaccess don't appear to work

### ISSUE THREAD

**Issue by DavidLoftus** [SFML/SFML-Website#141]
- Visiting https://www.sfml-dev.org/documentation/ results in `403 Forbidden` error.
- Visiting https://www.sfml-dev.org/documentation/latest results in `404 Not Found`.

Adding a forward slash to the URLs has no effect. I don't know about /latest but https://www.sfml-dev.org/documentation/ is used by [SFML's readme.md](https://github.com/SFML/SFML/blob/master/readme.md) which is currently broken. I was going to make a pull request there to make it 2.5.1 for docs and 2.5 for tutorial but it seems the real issue is on the website's end.

**Comment by eXpl0it3r** [comment]
Thanks for letting us know! Looks like the reverse proxy didn't allow for local overrides. This has now been fixed.
