### ISSUE TITLE
Replace `&#8209;` with `-`

### ISSUE THREAD

**Issue by andraantariksa** [SFML/SFML-Website#155]
https://github.com/SFML/SFML-Website/blob/0f05d6274b9bc6f867f88386d45cbcddf686eb63/tutorials/2.5/compile-with-cmake.php#L355

Why would the website use `&#8209;` to replace `-`?

I had a hard time after copy pasting a text from this website https://stackoverflow.com/questions/59573574/how-do-i-use-sfml-with-cmake-fetchcontent#comment105349020_59584360

**Comment by eXpl0it3r** [comment]
It's a non breaking dash, so I guess the idea was that you won't ever get something like the following rendered:

```
... sfml-system sfml-
window sfml-network ...
```

However as you pointed out when copy pasting it could lead to issues, so might make sense to change it.

Do you want to provide a pull request?

**Comment by eXpl0it3r** [comment]
![image](https://user-images.githubusercontent.com/920861/207660211-3fe80239-a312-4154-b21f-8989c79f67ce.png)

Hmm maybe we just need to add some min-width styling now 🤔

**Comment by andraantariksa** [comment]
120px looks fine for me
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/9760691/209959057-f4fae5f7-cc7a-439b-bdaa-701307b18bdc.png">
![www sfml-dev org_tutorials_2 5_compile-with-cmake php(iPhone 12 Pro)](https://user-images.githubusercontent.com/9760691/209959091-df178229-f1b7-4648-84ff-bf56c90f3136.png)

**Comment by eXpl0it3r** [comment]
Sounds good to me, do you want to PR it? 🙂
