### ISSUE TITLE
Link to the CMake project template from the tutorials

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML-Website#160]
https://github.com/SFML/cmake-sfml-project

Given how much we plug this project on Discord, we ought to mention it clearly on the website so that more folks doing web searches for SFML tutorials can find it.

I'm not exactly sure where the link(s) should go but the tutorials page is a good option. Maybe it's yet another option under "Getting Started" [here](https://www.sfml-dev.org/tutorials/2.5/ ).

**Comment by eXpl0it3r** [comment]
Related to #114 

I could imagine that we simply integrate the readme text into a new Getting Started page and potentially even list the CMake code, plus of course a link to the repo to quickly start with a simple cloning.

**Comment by eXpl0it3r** [comment]
Done with with #167 https://www.sfml-dev.org/tutorials/2.6/start-cmake.php
