### ISSUE TITLE
Update CSFLM bindings / binaries

### ISSUE THREAD

**Issue by CWBudde** [SFML/SFML-Website#17]
It seems that the CSFML is already available as v2.3 in the repository. Yet the binaries are missing on the website. Please update them soon as other bindings (such as PasSfml) depend on the C bindings.

**Comment by eXpl0it3r** [comment]
It's been tagged a few days ago and the binaries have not yet been built. Please be a bit more patient, we're not magician after all and like to enjoy a weekend or so. :wink:

**Comment by CWBudde** [comment]
I didn't want to stress anyone, but since the tagging is now already 3 weeks ago, I thought it was just forgotten. Also, I want to underline the importance for depending bindings.

**Comment by eXpl0it3r** [comment]
Added in b420726bfff6eafde94a4ec3ce74521fa2f07391
