### ISSUE TITLE
The word "soon" must be deleted on the official web site

### ISSUE THREAD

**Issue by 8Observer8** [SFML/SFML-Website#175]
Please, delete the `soon` word here:

![image](https://github.com/SFML/SFML-Website/assets/3908473/d5df4c26-3a54-4c4b-b785-87d3812f339e)

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML-Website/blob/c9cf0e0c9c449cf521979976ba110cab9d22a540/index.php#L34

Here's the line in question
