### ISSUE TITLE
[macOS] discrepancy between download label and binaries?

### ISSUE THREAD

**Issue by orazioedoardo** [SFML/SFML-Website#187]
The [download page](https://www.sfml-dev.org/download/sfml/2.6.1/) states that the macOS download is compatible with OS X 10.7 and later (on Intel obviously), however, when checking the [macOS 64-bit download](https://www.sfml-dev.org/files/SFML-2.6.1-macOS-clang-64-bit.tar.gz) it looks like it was built for macOS 10.15 and later (same for extlibs).

```
% find SFML-2.6.1-macOS-clang-64-bit -type f -exec vtool -arch x86_64 -show-build {} \; 2> /dev/null
[...]
./Frameworks/sfml-window.framework/Versions/2.6.1/sfml-window (architecture x86_64):
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 10.15
      sdk 10.15
   ntools 1
     tool LD
  version 857.1
[...]
```

Which is true?

Also why having a "64-bit" (x86_64) version and an "ARM64" version instead of an universal binary version? Both options already bundle universal binary extlibs anyways but not SFML itself. I find much more likely that someone would want to release an universal binary app these days rather than an apple silicon only version for example.

**Comment by eXpl0it3r** [comment]
> The [download page](https://www.sfml-dev.org/download/sfml/2.6.1/) states that the macOS download is compatible with OS X 10.7 and later (on Intel obviously), however, when checking the [macOS 64-bit download](https://www.sfml-dev.org/files/SFML-2.6.1-macOS-clang-64-bit.tar.gz) it looks like it was built for macOS 10.15 and later (same for extlibs).

Yes, I believe, I had to up the minimum version. Apple doesn't even officially provide old SDK versions, so you have to do some manual hacks to get this working. Feel free to send a PR to change the version.

> Also why having a "64-bit" (x86_64) version and an "ARM64" version instead of an universal binary version?

Because it's more work to rebundle everything and some said it's not worth it. Hopefully we can automate this process.

**Comment by eXpl0it3r** [comment]
Website has been updated: https://www.sfml-dev.org/download/sfml/2.6.1/

Thanks for raising and fixing this! 🙂
