### ISSUE TITLE
Remove extra backslashes on 3.0 window/window tutorial

### ISSUE THREAD

**Issue by HyperNervie** [SFML/SFML-Website#230]
On the [3.0 window/window tutorial page](https://www.sfml-dev.org/tutorials/3.0/window/window/), there are extra backslashes in the table explaining `sf::Style` enumerations. (corresponding to line 41 of [pages/tutorials/3.0/window/window.md](https://github.com/SFML/SFML-Website/blob/cce474544dad1e82492f7fa3f4047b52bab40cf5/pages/tutorials/3.0/window/window.md?plain=1#L41))

**Comment by eXpl0it3r** [comment]
Fixed with 9bb9a52194efddbfeae34cbafe673cb72a8d1420
