### ISSUE TITLE
Tutorials version

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML-Website#24]
This is rather minor, but I noticed two things about tutorials:

* 2.3 appears in the links to older versions, but since it is the latest version it shouldn't

* The main title is "Tutorials for SFML 2.3.x" but I would not have added this ".x". "SFML 2.3" is ok to refer to the whole 2.3.x branch, especially since the very first version is 2.3 and not 2.3.0. But yeah... that's really minor, I know :stuck_out_tongue:

**Comment by eXpl0it3r** [comment]
* Must have changed it before deciding not to double the tutorial.
* The first version is officially also 2.3.0 and the .x makes it clear for the people that his applies to 2.3 and 2.3.1 and 2.3.2, so they don't have to search frantically for the 2.3.1 like it is with all the other things.

**Comment by LaurentGomila** [comment]
> The first version is officially also 2.3.0

Everywhere I've checked (download section, release filenames), it was 2.3.

**Comment by eXpl0it3r** [comment]
Check the source code.

**Comment by LaurentGomila** [comment]
I know there's a SFML_VERSION_PATCH macro (it obviously has to be defined to 0 for a new minor release), if that's what you mean, but I'm talking about what *users* see on the website etc.

**Comment by Bromeon** [comment]
I agree with Laurent. Furthermore, since there is no API difference between patch versions, even "2.3" referring to the one version and not the whole branch would be correct. I wouldn't use "2.3.x" because it's not really a common term in our community...

**Comment by eXpl0it3r** [comment]
Fixed.
