### ISSUE TITLE
Allow tutorials to be adapted to other languages / programming languages

### ISSUE THREAD

**Issue by alanwillms** [SFML/SFML-Website#28]
As we have been [discussing here](http://en.sfml-dev.org/forums/index.php?topic=18762), the current website license does not allow to adapt tutorials texts.

The issue here is if someone writes bindings for another programming language, he must be able to adapt SFML tutorials examples to such bindings and publish them.

Copying @BlaXpirit @LaurentGomila

**Comment by TankOs** [comment]
#29

**Comment by eXpl0it3r** [comment]
Changed with commit 1e6ef9779cbad2261550027d7101c05107fedd6f

**Comment by alanwillms** [comment]
Thank you
