### ISSUE TITLE
Layout issue on french download page

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML-Website#38]
The last compiler line for Windows (GCC 4.9.2 MinGW (DW2) - 32-bit /	GCC 4.9.2 MinGW (SEH) - 64-bit) causes a layout bug on the french page, because there is not enough space for both the text and the button.

**Comment by eXpl0it3r** [comment]
Yeah, it was already a very close call for the English version.

I think the download page needs a change anyways, so we link directly to the used compilers (for Windows), maybe that will make it easier and reduce some help requests (hopefully).
