### ISSUE TITLE
tileset.png is nowhere to be found

### ISSUE THREAD

**Issue by zsbzsb** [SFML/SFML-Website#46]
The [tutorial that talks about vertex arrays](http://www.sfml-dev.org/tutorials/2.3/graphics-vertex-array.php#example-tile-map) includes an example for a tilemap. Problem is that the `tileset.png` is nowhere to be found. Its not in the directory with the other tutorial images or anywhere in the download section.

**Comment by LaurentGomila** [comment]
It's just a code snippet, not a project ready to compile and run. None of the resources demonstrated in the tutorials are directly downloadable.

**Comment by eXpl0it3r** [comment]
I guess we could think about providing a zip or so with the source and the code.

Or probably even better create a repo with lots of examples (extending the existing ones), but that would be a discussion for the forum.

**Comment by zsbzsb** [comment]
>It's just a code snippet, not a project ready to compile and run

I will agree that most of the code in just about all the tutorials is snippets, but in this case it is advertised as a complete example ready to run. That is why there is even a 'And now, the application that uses it:' that follows the ```TileMap``` class that is entirely complete minus the texture. And following the tilemap example, there is even a fully complete particle system which is ready to be copy-pasted and ran. This is why these two examples even include screenshots of the running code because they are complete.

Checkout the [custom audio stream tutorial](http://www.sfml-dev.org/tutorials/2.3/audio-streams.php#a-simple-example) and [threading](http://www.sfml-dev.org/tutorials/2.3/system-thread.php#protecting-shared-data) tutorial, they also unlike most of the tutorials advertise 'examples ready to run', not just snippets of code.

>None of the resources demonstrated in the tutorials are directly downloadable

The only other resource one of the complete examples require is the ```sound.wav``` from the custom audio streams tutorial. None of the other complete examples require resources except for the tilemap (which is by far the most popular tutorial).

>I guess we could think about providing a zip or so with the source and the code.

Why not just put the ```tileset.png``` and (some random) ```sound.wav``` in a ```/tutorials/downloads/``` folder and provide links from the tutorials? I would gladly make a PR doing this, problem is we need the original ```tileset.png``` that was used to generate the screenshots in the examples.

**Comment by LaurentGomila** [comment]
> @LaurentGomila I assume you have this?

Of course not ;)

But it can be reconstructed in 5 minutes, just copy the 4 tile types in a square image. However I have no idea where I got it from, so I don't know if we can redistribute it freely.

**Comment by gdinit** [comment]
Not the original file but a clone (recreated by myself (mpeg3 on the forums)) which does the job has been attached to the forum thread here:
http://en.sfml-dev.org/forums/index.php?topic=20654.msg148359#msg148359

You can download tileset.png there.

**Comment by eXpl0it3r** [comment]
Implemented in 116
