### ISSUE TITLE
Outdated info regarding the OpenGL CORE flag

### ISSUE THREAD

**Issue by SiXoS** [SFML/SFML-Website#49]
At the following page: http://www.sfml-dev.org/tutorials/2.0/window-opengl.php 
There is a warning box that says:
 > OpenGL versions above 3.0 are supported by SFML (as long as your graphics driver can handle them), but you can't set flags for now. This means that you can't create debug or forward compatible contexts; in fact SFML automatically creates contexts with the "compatibility" flag, because it uses deprecated functions internally. This should be improved soon, and flags will then be exposed in the public API.

This is not true since SFML 2.3. The core flag is now exposed and works fine. At the documentation for ContextSettings there is the following text:

> Warning: The graphics module will not function if you request a core profile context. Make sure the attributes are set to Default if you want to use the graphics module.

I don't know if this is still false as I don't use the graphics module. As the other text was outdated I thought this should be checked as well.

**Comment by binary1248** [comment]
If you look carefully at the link you pasted, it applies to SFML 2.0, so in that respect it is still correct. If you are using SFML 2.3 then you should refer to the corresponding documentation instead:
http://www.sfml-dev.org/tutorials/2.3/window-opengl.php
