### ISSUE TITLE
Gamejam Hall of fame

### ISSUE THREAD

**Issue by bitano79** [SFML/SFML-Website#51]
The Gamejam site could use a hall of fame section displaying all previously made gamejam games.

Additionally, it could keep track of gamejam scores allowing newer better rated games to get higher in the ranking of the hall of fame... This bit obviously requires some more thought (with regards to the actual ranking)

**Comment by eXpl0it3r** [comment]
The SFML Game Jam site is maintained by community members (@zsbzsb) and has nothing directly to do with the official SFML website. Feel free to join the [IRC channel](http://kiwiirc.com/client/irc.boxbox.org/#sfmlgamejam).

**Comment by zsbzsb** [comment]
We could always do a hall of fame on the jam site, so feel free to [make a pull request](https://github.com/zsbzsb/sfmlgamejam/fork).

**Comment by bitano79** [comment]
ooooh i thought i was using the proper route seeing as Erermell suggested i
post an Issue Request on github. Looks like i used the incorrect repository
(lol)

No worries! I'll poke zsbzsb. Thanks :-)
