### ISSUE TITLE
Broken link to tutorials

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML-Website#6]
Hi

Someone reported that http://www.sfml-dev.org/tutorials.php leads to a 404 error. Note that it seems to redirect to http://www.sfml-dev.org/resources.php first (which doesn't exist anymore).

**Comment by eXpl0it3r** [comment]
Since this is a nginx setting: @TankOs can you look into this?

**Comment by eXpl0it3r** [comment]
@TankOs fixed it. Tanks! :cat2:

**Comment by TankOs** [comment]
:+1: :cat2:
