### ISSUE TITLE
Replace deprecated functions in the tutorials

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#68]
Some tutorials still use functions which were declared as deprecated.

* [x] `LinesStrip`, `TrianglesFan` and `TrianglesStrip`.
* [x] `setParameter` and `setUniform` for `sf::Shader` #75
* [x] `setColor` vs `setFillColor` #76

**Comment by LaurentGomila** [comment]
The `graphics-vertex-array` tutorial uses deprecated primitive types: `LinesStrip`, `TrianglesFan` and `TrianglesStrip`.

**Comment by eXpl0it3r** [comment]
Same goes for `setParameter` and `setUniform` for `sf::Shader`.

**Comment by eXpl0it3r** [comment]
Fixed with #84.
