### ISSUE TITLE
Make the website use HTTPS

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#69]
With Let's Encrypt offering free certificates, it should be possible to make the website use HTTPS.

Note: For the forum we need to be careful, since this would pretty much disallow the embedding of non-HTTPS content (e.g. images).

**Note:** www.sfml-dev.org/ip-provider.php must remain accessible through HTTP since [it's used with SFML](https://github.com/SFML/SFML/blob/master/src/SFML/Network/IpAddress.cpp#L144) to determine the remote IP address.

**Comment by LaurentGomila** [comment]
Can you explain the benefits of switching to HTTPS?

**Comment by binary1248** [comment]
Logging in and posting stuff on the forum would be more secure and private? This question can be asked about every other website on the internet... Seeing how even the simplest and non-security-related websites are being offered in HTTPS I don't see why we shouldn't follow suit...

For the embedding part: Obviously there is a reason for this. I could imagine a proper implementation merely providing a link the user can click on for non-HTTPS content. Most content hosting sites are already offering HTTPS so this isn't even a real issue if you ask me.

**Comment by eXpl0it3r** [comment]
Additionally ISPs (and others) can't proxy your traffic and potentially insert any content they want (ads, tracking code, information popups, etc.) and yes those are things that are happening right now in many countries (Switzerland, UK, etc.).

**Comment by eXpl0it3r** [comment]
Website and forum are now being served over HTTPS.
