### ISSUE TITLE
mirror0.sfml-dev.org is broken

### ISSUE THREAD

**Issue by crumblingstatue** [SFML/SFML-Website#91]
[rust-sfml](https://github.com/jeremyletang/rust-sfml) builds on Travis have been failing a lot lately.
Here is the most recent failed build: https://travis-ci.org/jeremyletang/rust-sfml/jobs/215931724

It seems that the failures are caused by mirror0.sfml-dev.org not sending any data.
[Successful builds](https://travis-ci.org/jeremyletang/rust-sfml/jobs/215931725) seem to be using mirror3 (and possibly other mirrors).

**Comment by stschindler** [comment]
@crumblingstatue Thanks for reporting. It's fixed now.

**Comment by TankOs** [comment]
@crumblingstatue Thanks for reporting, it's fixed now.

**Comment by crumblingstatue** [comment]
Thank you for the quick response and fix!
