### ISSUE TITLE
Replace misleading space separated VS library list screenshot

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML-Website#95]
The tutorial screenshot for VS shows the libraries to link listed with spaces as separator. In all the VS versions I've used, starting from VS 2010, the list however uses semicolon separators. As I see others screenshots with spaces, I have to assume that some earlier version used spaces.

To reduce confusion and raise correctness, the screenshot should be updated.

Maybe update all the VS screenshots? 🤔

**Comment by LaurentGomila** [comment]
Or we could use GIMP to paste semicolons into those spaces, so that we don't have to update everything 😆

**Comment by eXpl0it3r** [comment]
I didn't use GIMP, but that's exactly what I did. 😄 

Fixed in 2f4ad7be421e1257dae430899aa0299dcde567ed
